# Generated by Django 4.2 on 2023-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('p_name', models.CharField(max_length=100)),
                ('p_age', models.IntegerField()),
                ('p_gender', models.CharField(max_length=20)),
                ('p_dob', models.DateField()),
                ('p_phone', models.CharField(max_length=20)),
            ],
        ),
    ]
